// ch10/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import "./hello-world.js";
  import "./radio-group.js";

  const initialColor = "red";
  let helloWorldElement: HTMLElement | undefined = undefined;
  let radioGroupElement: HTMLElement | undefined = undefined;

  onMount(() => {
    const color = radioGroupElement
      ? (radioGroupElement as any).value
      : "black";
    updateColor(color);
  });

  function handleChange(event: CustomEvent) {
    updateColor(event.detail.value);
  }

  function updateColor(color: string) {
    if (helloWorldElement) (helloWorldElement as any).color = color;
  }
</script>

<main>
  <hello-world name="Mark" bind:this={helloWorldElement}></hello-world>
  <radio-group
    name="color"
    bind:this={radioGroupElement}
    labels="Red,Green,Blue"
    value={initialColor}
    values="red,green,blue"
    on:change={handleChange}
  ></radio-group>
</main>

// ch10/solid/src/App.tsx
import { onMount } from "solid-js";
import "./hello-world.js";
import "./radio-group.js";

function App() {
  const initialColor = "red";
  let helloWorldRef: HTMLElement | null = null;
  let radioGroupRef: HTMLElement | null = null;

  onMount(() => {
    const color = radioGroupRef ? (radioGroupRef as any).value : "black";
    updateColor(color);
  });

  function handleChange(event: Event) {
    const color = (event as CustomEvent).detail.value;
    updateColor(color);
  }

  function updateColor(color: string) {
    if (helloWorldRef) (helloWorldRef as any).color = color;
  }

  return (
    <>
      <hello-world name="Mark" ref={helloWorldRef}></hello-world>
      <radio-group
        name="color"
        labels="Red,Green,Blue"
        ref={radioGroupRef}
        value={initialColor}
        values="red,green,blue"
        onChange={handleChange}
      ></radio-group>
    </>
  );
}

export default App;
