// ch10/react/src/App.tsx
import { useEffect, useRef } from "react";
import "./App.css";
import "./hello-world.js";
import "./radio-group.js";

function App() {
  let helloWorldRef = useRef<HTMLElement | null>(null);
  let radioGroupRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    const { current } = radioGroupRef;
    const color = current ? (current as any).value : "black";
    updateColor(color);
  }, []);

  function handleChange(event: Event) {
    const { value } = event.target as HTMLInputElement;
    updateColor(value);
  }

  function updateColor(color: string) {
    const { current } = helloWorldRef;
    if (current) (current as any).color = color;
  }

  return (
    <>
      <hello-world name="Mark" ref={helloWorldRef}></hello-world>
      <radio-group
        labels="Red,Green,Blue"
        name="primaryColor"
        ref={radioGroupRef}
        values="red,green,blue"
        value="red"
        onChange={handleChange}
      ></radio-group>
    </>
  );
}

export default App;

// ch10/solid/src/App.tsx
import { onMount } from "solid-js";
import "./hello-world.js";
import "./radio-group.js";

function App() {
  const initialColor = "red";
  let helloWorldRef: HTMLElement | null = null;
  let radioGroupRef: HTMLElement | null = null;

  onMount(() => {
    const color = radioGroupRef ? (radioGroupRef as any).value : "black";
    updateColor(color);
  });

  function handleChange(event: Event) {
    const color = (event as CustomEvent).detail.value;
    updateColor(color);
  }

  function updateColor(color: string) {
    if (helloWorldRef) (helloWorldRef as any).color = color;
  }

  return (
    <>
      <hello-world name="Mark" ref={helloWorldRef}></hello-world>
      <radio-group
        name="color"
        labels="Red,Green,Blue"
        ref={radioGroupRef}
        value={initialColor}
        values="red,green,blue"
        onChange={handleChange}
      ></radio-group>
    </>
  );
}

export default App;
