// ch10/vue/src/App.vue
<script setup>
import { onMounted, ref } from "vue";
import "./hello-world.js";
import "./radio-group.js";

const initialColor = "red";
const helloWorldElement = ref(null);

onMounted(() => {
  updateColor(initialColor);
});

function handleChange(event) {
  updateColor(event.detail.value);
}

function updateColor(color) {
  const { value } = helloWorldElement;
  if (value) value.color = color;
}
</script>

<template>
  <hello-world name="Mark" ref="helloWorldElement"></hello-world>
  <radio-group
    name="color"
    labels="Red,Green,Blue"
    values="red,green,blue"
    :value="initialColor"
    @change="handleChange"
  ></radio-group>
</template>

// ch11/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import "./hello-world.js";
  import "./radio-group.js";

  const initialColor = "red";
  let helloWorldElement: HTMLElement | undefined = undefined;
  let radioGroupElement: HTMLElement | undefined = undefined;

  onMount(() => {
    const color = radioGroupElement
      ? (radioGroupElement as any).value
      : "black";
    updateColor(color);
  });

  function handleEvent(event: CustomEvent) {
    updateColor(event.detail.value);
  }

  function updateColor(color: string) {
    if (helloWorldElement) helloWorldElement.style.color = color;
  }
</script>

<main>
  <hello-world name="Mark" bind:this={helloWorldElement}></hello-world>
  <radio-group
    name="color"
    bind:this={radioGroupElement}
    labels="Red,Green,Blue"
    value={initialColor}
    values="red,green,blue"
    on:change={handleEvent}
  ></radio-group>
</main>
